# Language used for messages in the plugin
language: en

timer:
  delay: 1 # time in seconds (each second we will check if block can be replaced)
  respawn:
    enabled: true # to prevent block respawning
    range: # time in seconds
      min: 1
      max: 5

# Chance to get rewards
# 0 -> 0% of chance to get rewards
# 100 -> 100% of chance to get rewards
# Smaller the number, smaller the chance of getting a reward
breakChance:
  enable: false
  chance: 50

replacingBlock:
  type: STONE

# support %player%
rewardCommands:
  - give %player% diamond 1